spring.application.name=Nexowear

# Configuraci\u00f3n de Conexi\u00f3n
spring.datasource.url=jdbc:mysql://localhost:3306/nexowear_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Borra o comenta la l\u00ednea de MySQL8Dialect. 
# Spring Boot y Hibernate 7 detectar\u00e1n la versi\u00f3n de MySQL solos.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CONFIGURACIÓN DE JWT
# La firma debe ser una cadena larga y segura en texto plano (mínimo 64 caracteres)
nexowear.jwt.secret=TuClaveSecretaSuperSeguraYMuyLargaParaNexoWear2026!!!_AsegurandoElSistemaConMasDe64CaracteresDeLargo
# Tiempo de expiración del token en milisegundos (Ejemplo: 86400000 ms = 24 horas)
nexowear.jwt.expiration=86400000    

logging.level.org.springframework.security=DEBUG